#!/usr/bin/env python3
"""Gate 25 A7: the figure/text reconciliation table.

Every row was established by comparing a rendered figure against the manuscript
text and against the results file the figure is built from. Kept as a script
rather than a hand-written CSV so out/results/ has no orphan and the table can be
regenerated.
"""
from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "out" / "results" / "gate25_figure_text_reconciliation.csv"

HEADER = ['figure', 'discrepancy', 'severity', 'source_results_file', 'generating_script', 'source_superseded', 'status']

ROWS = [
    ('Figure 1', 'EC-PA disattenuated bars sit flat at rho=1.0 for reliability 0.5 and 0.7; true values 1.51/1.08 (tx) and 1.48/1.06 (tl). NOT an axis artifact: scripts/72 stores min(corrected,1.0) and records clipped_at_1, so the cap is in the data.', 'major', 'out/results/gate8_attenuation_analysis.json', 'scripts/73_attenuation_figures.py', 'no', 'FIXED - uncapped values annotated above a rho=1 line; caption discloses the cap'),
    ('Figure 1', "clipped_at_1 is serialised as the STRING 'True'/'False' by json.dump(default=str) on a numpy bool, so any truth test on it matches both.", 'minor', 'out/results/gate8_attenuation_analysis.json', 'scripts/72_attenuation_analysis.py', 'no', 'REPORTED - results file not rewritten; figure code compares the string explicitly'),
    ('Figure 1', "in-figure title asserted a claim ('EC-PA gap survives BS-pairs at every tested reliability') rather than describing the panel.", 'minor', '-', 'scripts/73_attenuation_figures.py', 'no', 'FIXED - title now descriptive'),
    ('Figure 2a', 'none found; every value reconciles with section 3.1.', 'none', 'out/results/gate10_5_gc_confound.json', 'scripts/96_gate10_5_figures.py', 'no', 'NO CHANGE - regenerated byte-identical'),
    ('Figure 2b', 'figure shows FOUR phylum strata; caption and section 3.1 named only two. Unnamed strata: Actinobacteria EC-PA 0.693 (n=824), Bacteroidetes EC-PA 0.536 (n=842).', 'major', 'out/results/gate10_5_gc_confound.json', 'scripts/96_gate10_5_figures.py', 'no', 'FIXED - all four reported in 3.1 with N; N added to every bar; caption updated'),
    ('Figure 2b', "section 3.1 said 'B. subtilis pairs near zero'. True range across the four strata is -0.209 to +0.271; Firmicutes BS-PA is +0.271 and EC-BS +0.177.", 'major', 'out/results/gate10_5_gc_confound.json', 'scripts/95_gc_confound_invivo.py', 'no', 'FIXED - text now states the range'),
    ('Figure 2b', 'results file holds SEVEN transcription strata; the figure hardcodes four. Cyanobacteria has all three pairs above threshold (EC-BS 0.332 n=62, EC-PA 0.543 n=455, BS-PA -0.022 n=44) and could be shown.', 'minor', 'out/results/gate10_5_gc_confound.json', 'scripts/96_gate10_5_figures.py', 'no', 'REPORTED - not added; changing which strata appear is a content decision'),
    ('Figure 3', 'cell-free EC-BS bar read 0.597, which appears nowhere in the manuscript. CONFIRMED STALE: it is the Gate 10 value, DRAFTS EC-BS on the 82-sequence Johns overlap, computed before Gate 15 defined the restriction regimes.', 'blocking', 'out/results/gate10_modality_comparison.json', 'scripts/94_gate10_figures.py', 'YES - superseded by out/results/gate15_coactive_modality.csv', 'FIXED - panel A rebuilt from current analysis, four bars'),
    ('Figure 3', 'panel A showed three bars (cell-free 0.597, n=15 overlap 0.147, full-library in-vivo 0.258); the caption described pooled and co-active regimes with four n values. Caption and panel described different comparisons.', 'blocking', 'out/results/gate10_modality_comparison.json', 'scripts/94_gate10_figures.py', 'YES', 'FIXED - panel now shows 0.616/0.655/0.677/0.258 with their N'),
    ('Figure 3', 'panel B (within-species RS234, seven species) was not mentioned in the caption at all. Its values 0.69-0.90 do reconcile with section 3.2.', 'major', 'out/results/gate10_modality_comparison.json', 'scripts/94_gate10_figures.py', 'no', 'FIXED - caption now describes both panels; per-species N added to bars'),
    ('Figure 3', "the n=15 paired estimate appeared as a bar although the text explicitly declines to use it as evidence (it was labelled 'unreliable').", 'major', 'out/results/gate10_modality_comparison.json', 'scripts/94_gate10_figures.py', 'no', 'FIXED - removed from the figure; still reported in Limitations item 5'),
    ('Figure 4', 'none found; the 8 primary comparisons reconcile with section 3.5.', 'none', 'out/results/gate5_hmain_table.csv', 'scripts/55_gate5_figures.py', 'no', 'NO CHANGE'),
    ('Figure 5', 'caption promised a panel (b) showing fold-to-fold standard deviation. No such panel exists; that content is Figure 7.', 'major', 'out/results/gate6_full_comparison.csv', 'scripts/65_gate6_figures.py', 'no', 'FIXED - caption rewritten'),
    ('Figure 5', 'caption named four systems; the figure shows six (DNABERT-2 and PromoGen2 included).', 'major', 'out/results/gate6_full_comparison.csv', 'scripts/65_gate6_figures.py', 'no', 'FIXED - caption names all six'),
    ('Figure 5', 'section 3.5 cites this figure for concatenation 0.555 and per-host-heads 0.615 at EC transcription. Neither system is plotted here.', 'major', 'out/results/gate6_full_comparison.csv', 'scripts/65_gate6_figures.py', 'no', 'REPORTED - caption now says those two are tabulated not plotted; whether to add them is a content decision'),
    ('Figure 5', "panels did not share a y-axis: BS transcription topped at ~0.28 against EC's ~0.7, flattering weak B. subtilis performance.", 'major', 'out/results/gate6_full_comparison.csv', 'scripts/65_gate6_figures.py', 'no', 'FIXED - sharey across all six panels'),
    ('Figure 6', 'none found; ECE values reconcile exactly with section 3.6 (EC 0.053/0.099, BS 0.429/0.344, PA 0.474/0.431).', 'none', 'out/results/gate7_conformal_calibration.json', 'scripts/68_conformal_calibration.py', 'no', 'NO CHANGE - title de-gated only'),
    ('Figure 7', 'none found; fold-to-fold values reconcile with section 3.7.', 'none', 'out/results/gate8_6_mechanism_fold_variance.csv', 'scripts/87_gate8_6_figures.py', 'no', 'NO CHANGE - x-labels de-ambiguated'),
    ('Figure 8', 'REPORT REFUTED: the figure shows 11 bar groups, not 12, matching the 11 cells in the text. The source CSV has exactly 11 rows.', 'none', 'out/results/gate8_6_shift_controls_decisive_comparison.csv', 'scripts/87_gate8_6_figures.py', 'no', 'NO CHANGE NEEDED - count was already correct'),
    ('Figure 8', "x-labels abbreviated BOTH 'transcription' and 'translation' to 'tr' via readout[:2], so PA_to_EC transcription and PA_to_EC translation rendered identically. This is the likely cause of the miscount.", 'major', 'out/results/gate8_6_shift_controls_decisive_comparison.csv', 'scripts/87_gate8_6_figures.py', 'no', 'FIXED - now tx / tl'),
    ('Figure 8', "in-figure title said '1 of 11 survives' while section 3.8 says reference-only matched or beat the model in 10 of 11. Same fact stated inversely.", 'minor', 'out/results/gate8_6_shift_controls_decisive_comparison.csv', 'scripts/87_gate8_6_figures.py', 'no', 'FIXED - title now states both directions'),
    ('Figures 1,5,6,8', "in-figure titles carried internal pipeline nomenclature: 'Gate 8 Task 1', 'Gate 6', 'Gate 7 Task 2', 'Gate 8.6 Task 1'.", 'minor', '-', 'scripts/73, 65, 68, 87', 'no', 'FIXED - all internal gate references removed'),
    ('ALL main figures', 'NO script produced out/PREPRINT/figures/*.png. Producers write out/figures/gate*.png; Gate 12 renamed copies by hand. audit_provenance.py passed only because the Gate 20 embed script mentions every preprint filename - a false pass on all nine files.', 'major', '-', 'scripts/106_gate25_regenerate_figures.py (new)', 'no', 'FIXED - one script now regenerates and places all nine, so provenance is real'),
]


def main() -> int:
    with open(OUT, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(HEADER)
        w.writerows(ROWS)
    from collections import Counter
    c = Counter(r[2] for r in ROWS)
    print(f"Wrote {OUT}: {len(ROWS)} rows, {dict(c)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
